config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users
  resources :users
  delete 'recipes/:id', to: 'recipes#destroy'
  patch 'recipes/:id', to: 'recipes#update'
  get 'recipes/:id/edit', to: 'recipes#edit', as: 'edit_recipe'
  post '/create_recipe', to: 'recipes#create'
  get '/recipes', to: 'recipes#index'
  get '/recipes/new', to: 'recipes#new'
  get '/recipes/:id', to: 'recipes#show', as: :recipe
  # Defines the root path route ("/")
  root to: 'recipes#public_recipes'
  get '/foods', to: 'food#index'
  get '/add_food', to: 'food#add'
  get '/public_recipes', to: 'recipes#public_recipes'
  post '/create_food', to: 'food#create'
  delete '/delete_food/:id', to: 'food#delete'

  get '/shopping_list/:id', to: 'recipes#shopping_list'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'
  has_many :recipes, through: :recipe_foods, dependent: :delete_all
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, :preparation_time, :cooking_time, :description, :public, presence: true
  belongs_to :user, foreign_key: 'user_id'
  has_many :food, through: :recipe_foods
  has_many :recipe_foods, dependent: :destroy
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe, foreign_key: 'recipe_id'
  belongs_to :food, foreign_key: 'food_id'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipe, foreign_key: 'user_id'
  has_many :food, foreign_key: 'user_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def logging_out; end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }

    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/food_controller.rb
class FoodController < ApplicationController
  def index
    @all_food = Food.where(user_id: current_user.id)
  end

  def new
    @new_food = Food.new
  end

  def create
    @new_food = Food.create(name: params[:name], measurement_unit: params[:measurement_unit], price: params[:price],
                            quantity: params[:quantity], user_id: current_user.id)
    @new_food.save
    redirect_to foods_path
  end

  def delete
    @food_to_delete = Food.find(params[:id])
    @food_to_delete.destroy
    redirect_to foods_path
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @user = current_user
    @recipes = @user&.recipe
  end

  def public_recipes
    @public_recipes = Recipe.includes(:user).all.where(public: true).order(created_at: :desc)
    render :public_recipes
  end

  def new
    @recipe = Recipe.new
  end

  def create
    recipe = Recipe.create(
      name: params[:name],
      preparation_time: params[:prepration_time],
      cooking_time: params[:cooking_time],
      description: params[:description],
      public: params[:public],
      user_id: current_user.id
    )
    puts recipe.name, recipe.preparation_time, recipe.cooking_time, recipe.description, recipe.public, recipe.user_id,
         recipe.valid?
    if recipe.save
      redirect_to recipes_path, notice: 'Recipe created successfully!'
    else
      render new, status: :unprocessable_entity, alert: 'An error has occurred while creating the new recipe'
    end
  end

  def update
    if @recipe.update(recipes_params)
      redirect_to recipes_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  # GET /recipes/1 or /recipes/1.json
  def show; end

  def delete
    @recipe = Recipe.find(params[:id])
    if @recipe.destroy
      redirect_to recipes_path, notice: 'Recipe deleted Successfully'
    else
      redirect_to root, alert: 'Could not delete recipe'
    end
  end

  def shopping_list
    @recipe_shopping = Recipe.find(params[:id]).recipe_foods
    @food = []
    @recipe_shopping.ids.each do |id|
      @food.push(Food.find_by(id:))
    end
    @user_food = current_user.food
    @comparison_food = custom_difference(@food, @user_food)
    @food.each do |a|
      puts a.name
    end
    puts 'hello'
    @user_food.each do |a|
      puts a.name
    end
    same_food_result = same_food(@food, @user_food)
    if same_food_result.zero?
      @comparison_food
    else
      @comparison_food.append(same_food(@food, @user_food))
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end

  def custom_difference(all, subset)
    all.select do |all_curr|
      subset.find do |subset_curr|
        subset_curr.name == all_curr.name
      end.nil?
    end
  end

  def same_food(_food, _user_food)
    @comparis_food = []
    @user_food.each do |uf|
      @food.each do |rf|
        next unless uf.name == rf.name
        next if (uf.quantity - rf.quantity).zero?

        uf.quantity = uf.quantity - rf.quantity
        @comparis_food.push(uf)
      end
    end
    if @comparis_food.count.zero?
      0
    else
      @comparis_food
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_helper.rb
module FoodHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/food/add.html.erb
<div class="add_food_form_container">
  <%= form_with model: @new_food, url: "/create_food", html: {class: "add_food_form"} do |f| %>
    
    <div class="field">
      <%= f.text_field :name, placeholder: "name" %>
    </div>

    <div class="field">
      <%= f.text_field :measurement_unit, placeholder: "measurement_unit" %>
    </div>

    <div class="field">
      <%= f.text_field :price, placeholder: "price" %>
    </div>

    <div class="field">
      <%= f.text_field :quantity, placeholder: "quantity" %>
    </div>

    <div class="actions">
      <%= f.submit "Add Food" %>
    </div>
  <% end %>
</div>

app/views/food/index.html.erb
<div class="food_container">
  <a href="/add_food" class="add_food">
    <p>Add Food</p>
  </a>
  <table>
    <tr>
      <th>Food</th>
      <th>Measurement Unit</th>
      <th>Quantity</th>
      <th>Unit Price</th>
      <th>Actions</th>
    </tr>
    <% @all_food.each do |f| %>
    <tr>
      <td><%= f.name %></td>
      <td><%= f.measurement_unit %></td>
      <td><%= f.quantity %></td>
      <td><%= f.price %></td>
      <td>
        <%= form_with url: "/delete_food/#{f.id}", method: :delete do |form| %>
          <%= form.submit("Delete") %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/layouts/_navbar.html.erb
<% if user_signed_in? %>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">

    <%= link_to 'Public Recipes', root_path , class: "navbar-brand"%>
    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'My Recipes', recipes_path , class: "nav-link"%>
        </li>

        <li>
          <li class="nav-item">
            <%= link_to "Foods", foods_path, class: 'nav-link'%>
          </li>
        </li>
      </ul>
      <div class="d-flex" role="delete">
        <%= button_to "Sign out", destroy_user_session_path, class:"btn btn-outline-success", :method => :delete%>
      </div>
    </div>
    </div>
  </nav>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipe App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application.tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="">
      <%= render "layouts/navbar" %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
  </body>
</html>

app/views/recipes/_form.html.erb
<div class="container w-full max-w-lg mx-auto pt-5">
<% if recipe.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

    <ul>
    <% recipe.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  
  <%= form_with url: "/create_recipe", class: "recipe-form flex flex-wrap -mx-3 mb-6" do |form| %>
    <%= form.text_field :name, placeholder: 'Name', class:"appearance-none block w-full bg-gray-200 text-gray-700 border border-red-500 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white"%>
      <br>
      <%= form.number_field :preparation_time, placeholder: 'Preparation time', class:"appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" %>
      <br>
      <%= form.number_field :cooking_time, placeholder: 'Cooking time', class:"appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 mt-2 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" %>
      <br>
      <%= form.text_area :description, placeholder: 'Description', class: "text_area mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" %>
      <br>
      <%= form.label :public, "Public: true/false " %>
      <%= form.select :public, options_for_select([true, false]), class:"block appearance-none w-full bg-gray-200 border border-gray-200 text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500" %>
      <br>
      <%= form.submit "Add Recipe",  class: "btn ml-5 rounded-md border border-gray-300 bg-white py-2 px-3 text-sm font-medium leading-4 text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
    <% end %>
</div>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>" class="flex flex-col">
  <h2 class="grid place-items-center font-bold text-xl"><%= recipe.name %></h2>
  <p>Preparation Time: <%= recipe.preparation_time %> hours </p>
  <p>Cooking Time: <%= recipe.cooking_time %> hours </p>
  <p>Steps go here....</p>

</div>

app/views/recipes/edit.html.erb
<h1 class="font-medium leading-tight text-5xl mt-0 mb-2 text-blue-600 mx-auto">Editing Recipe</h1>
<%= render "form", recipe: @recipe %>

app/views/recipes/index.html.erb
<div class="recipe-list">
  <div>
    <%= link_to "New Recipe", recipes_new_path, class:"no-underline hover:underline text-purple-700 text-lg" %>
  </div>
  <ul class="border-2 border-gray-600">
    <% if @recipes&.empty? %>
      <p>No recipes to show!</p>
      <%else%>
      <% @recipes&.each do |recipe| %>
      <li class="recipe-card flex divide-x divide-gray-400 m-6 p-8">
        <div class="w-40">
        <h2><%= link_to recipe.name, recipe_path(recipe.id), class:"no-underline hover:underline text-blue-500 text-lg" %></h2>
        <%= button_to "Delete", recipe , method: :delete, class:"bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
        </div>
        <div class="pl-2">
          <p><%= recipe.description %></p>
        </div>
      <li>
      
      <% end %>
    <%end%>
  </ul>
</div>

app/views/recipes/new.html.erb
<h1 class="font-medium leading-tight text-5xl mt-0 mb-2 text-blue-600 mx-auto">New Recipe</h1>
<%= render "form", recipe: @recipe %>

app/views/recipes/public_recipes.html.erb
<div class="public_recipes">
  <h1>Public Recipes</h1>
  <% if @public_recipe == nil %>
  <% else  %>
    <% @public_recipe.each do |p| %>
      <div class="public_recipe_container">
        <div class="public_recipe_details">
          <h2>
            <%= link_to p.name, recipe_path(p.id), class:"recipe-title" %>
          </h2>
          <h3>By: <%= p.user.name %></h3>
        </div>
        <div class="public_recipe_numerics">
          <h3>Total Food Items: <%= p.recipe_foods.count %></h3>
          <h3>Total Price : 
            <% sum = 0 %>
            <% p.recipe_foods.each do |rp| %>
              <% sum += rp.quantity * rp.food.price %>
            <% end %>
            $<%= sum %>
          </h3>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/recipes/shopping_list.html.erb
<div class="shopping_list_container">
  <h1>Shopping List</h1>
  <h4>Amount of food items to buy: <%= @comparison_food.count %>  Total value of food needed: 
    <% sum = 0 %>
    <% @comparison_food.each do |cf| %>
      <% sum += cf.quantity * cf.price %>
    <% end %>
    <%= sum %>
  <h4>
  
  <br />
  <% if @comparison_food.count == 0 %>
    <p>You have all the ingredients</p>
  <% else %>
    <table>
      <tr>
        <th>Food</th>
        <th>Quantity</th>
        <th>Price</th>
      </tr>
      <% @comparison_food.each do |f| %>
      <tr>
        <td><%= f.name %></td>
        <td><%= f.quantity %> <%= f.measurement_unit %></td>
        <td><%= f.price %></td>
      </tr>
      <% end %>
    </table>
  <% end %>
</div>

app/views/recipes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @recipe %>

<div class="container mx-auto mt-28 px-5 ">
 
  <%= link_to "Back to recipes", recipes_path, class:"no-underline hover:underline text-purple-700 text-lg"%>
  <%= link_to "Generate Shopping List", "/shopping_list/#{@recipe.id}", class:"no-underline hover:underline text-purple-700 text-lg"%>


<table class="table-auto min-h-full border-2 border-gray-600">
  <thead>
    <tr class="divide-x">
      <th class="flex align-left pl-1">Food</th>
      <th class="ml-0">Quantity</th>
      <th class="flex pl-1">Value</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
  <% %>
     <tr
      key={mission.mission_id}
      class="odd:bg-gray-200 divide-x divide-gray-300"
    >
      <td class="flex align-top m-auto"><%= @recipe.name %></td>
      <td class="px-3 py-2"><%= @quantity %></td>
      <td><%= @price %></td>
      <td>
          <div class="status w-64 flex justify-around text-xs">
            <span class="badge bg-blue-400 text-white rounded-sm px-1 py-0.5 uppercase grid place-items-center">
               <%= link_to "Edit this recipe", edit_recipe_url(@recipe) %>
            </span>
          </div>
      </td>
      <td>
          <div class="w-64 flex justify-around text-xs">
            <button
              type="button"
              class="text-sm text-red-600 border-red-400 rounded-sm border-2 px-1 py-0.5"
            >
              <%= link_to "Delete this recipe", recipe_url(@recipe), method: :delete, data: { confirm: "Are you sure?" } %>
            </button>
          </div>

      </td>
    </tr>
  </tbody>
</table>


</div>